name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STAGE: TEST

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry lock --check
      - run: poetry install
      - run: poetry run pytest --cov src/service_template --cov-report term --cov-report html
      - run: poetry run black --check .
      - name: mypy
        run: poetry run mypy src/service_template --strict --txt-report .mypy && cat .mypy/index.txt
      - run: sh check_contains_template.sh
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      STAGE: test
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install --only main
      - run: |
          python3.8 -m venv deploy-env
          source deploy-env/bin/activate
          pip install -r requirements.txt
          pip install zappa
          pip install -e .

      - name: deploy dev
        run: |
          source deploy-env/bin/activate
          python deploy_helper.py dev
          zappa update dev

      - name: deploy production
        if: github.event_name == 'push'
        run: |
          source deploy-env/bin/activate
          python deploy_helper.py production
          zappa update production
